title: ScrambledPhysics
description: |
  ScrambledPhysics is a simple physics library for the Processing language,
  written in pure processing, in a single file.

theme: jekyll-theme-minimal
show_downloads: true

sass:
    style: compressed
